name: apicurio-registry
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  register_asyncapi_in_apicurio_registry:
    runs-on: ubuntu-latest
    name: Register AsyncAPI definitions in Apicurio Registry
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install yq
        uses: mikefarah/yq@v4.14.1

      - name: Run script
        env:
          APICURIO_REGISTRY_API_KEY: ${{ secrets.APICURIO_REGISTRY_API_KEY }}
          APICURIO_REGISTRY_API_KEY_SECRET: ${{ secrets.APICURIO_REGISTRY_API_KEY_SECRET }}
          APICURIO_REGISTRY_URL: ${{ secrets.APICURIO_REGISTRY_URL }}
        run: |
          scripts/register-asyncapi-apicurio.sh \
              --apicurio-registry-url ${APICURIO_REGISTRY_URL} \
              --basic-auth "${APICURIO_REGISTRY_API_KEY}:${APICURIO_REGISTRY_API_KEY_SECRET}"
